Repository milieuinfo/webcomponent-vl-ui-rich-data-table, pull requests merged in 2020-06, with the labels that each got.

#56 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/performance.html
  demo/vl-rich-data-table.html
  index.js
  package-lock.json
  package.json
  performance/README.md
  performance/config/budget.json
  performance/config/config-chrome.json
  performance/config/config-firefox.json
  performance/scripts/preScript.js
  src/index.js
  src/vl-rich-data-field.js
  src/vl-rich-data-sorter.js
  src/vl-rich-data-table.js
  test/e2e/components/vl-rich-data-sorter.js
  test/e2e/components/vl-rich-data-table.js
  test/e2e/pages/vl-rich-data-table.page.js
  test/e2e/rich-data-table.test.js
  test/unit/vl-rich-data-field.test.html
  test/unit/vl-rich-data-sorter.test.html
  test/unit/vl-rich-data-table-and-field.test.html
  test/unit/vl-rich-data-table-filter.test.html
  test/unit/vl-rich-data-table-paging.test.html
  test/unit/vl-rich-data-table-sorting.test.html
  test/unit/vl-rich-data-table.test.html
Labels: chore

#54 Introductie renderer functie
  clone.js
  demo/vl-rich-data-table.html
  dist/vl-rich-data-field.js
  dist/vl-rich-data-field.min.js
  dist/vl-rich-data-field.src.js
  dist/vl-rich-data-sorter.js
  dist/vl-rich-data-sorter.min.js
  dist/vl-rich-data-sorter.src.js
  dist/vl-rich-data-table.js
  dist/vl-rich-data-table.min.js
  dist/vl-rich-data-table.src.js
  package-lock.json
  package.json
  src/vl-rich-data-field.js
  src/vl-rich-data-sorter.js
  src/vl-rich-data-table.js
  test/e2e/rich-data-table.test.js
  test/unit/vl-rich-data-field.test.html
  test/unit/vl-rich-data-table-filter.test.html
Labels: enhancement

#62 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#65 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  test/docker-compose.yml
Labels: chore

#64 Sta toe dat men geen label definieert voor een vl-rich-data-field
  package-lock.json
  src/vl-rich-data-field.js
  src/vl-rich-data-table.js
  test/unit/vl-rich-data-field.test.html
  test/unit/vl-rich-data-table-and-field.test.html
Labels: enhancement
