Repository milieuinfo/webcomponent-vl-ui-rich-data-table, pull requests merged in 2020-04, with the labels that each got.

#42 Filter rendering in een modal voor mobiele toestellen
  demo/vl-rich-data-table.html
  dist/index.js
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-rich-data-sorter.js
  dist/vl-rich-data-sorter.min.js
  dist/vl-rich-data-sorter.src.js
  dist/vl-rich-data-table.js
  dist/vl-rich-data-table.min.js
  dist/vl-rich-data-table.src.js
  package-lock.json
  package.json
  src/vl-rich-data-table.js
  test/e2e/components/vl-rich-data-table.js
  test/e2e/rich-data-table.test.js
  test/unit/vl-rich-data-table-filter.test.html
Labels: enhancement

#43 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#47 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  demo/performance.html
  docker-compose-performance-chrome.yml
  docker-compose-performance-firefox.yml
  package-lock.json
  package.json
  performance/README.md
  performance/config/budget.json
  performance/config/config-chrome.json
  performance/config/config-firefox.json
  performance/scripts/preScript.js
Labels: chore

#49 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
