Repository milieuinfo/webcomponent-vl-ui-rich-data-table, pull requests merged in 2020-07, with the labels that each got.

#68 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#69 Update dependencies
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/e2e/rich-data-table.test.js
Labels: chore

#67 Introductie vl-ui-rich-data
  demo/vl-rich-data-table.html
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-rich-data-field.js
  dist/vl-rich-data-field.src.js
  dist/vl-rich-data-table.js
  dist/vl-rich-data-table.min.js
  dist/vl-rich-data-table.src.js
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-rich-data-field.js
  src/vl-rich-data-table.js
  test/e2e/components/vl-rich-data-table.js
  test/e2e/rich-data-table.test.js
  test/unit/vl-rich-data-field.test.html
  test/unit/vl-rich-data-sorter.test.html
  test/unit/vl-rich-data-table-and-field.test.html
  test/unit/vl-rich-data-table-filter.test.html
  test/unit/vl-rich-data-table-paging.test.html
  test/unit/vl-rich-data-table-sorting.test.html
  test/unit/vl-rich-data-table.test.html
Labels: enhancement
